#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"; TMP="$(mktemp -d "${TMPDIR:-/tmp}/wheelhouse-codex-selftest.XXXXXX")"; trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/bin" "$TMP/home" "$TMP/proj/contracts" "$TMP/proj/.wheelhouse-worktrees/bead-a"
cat > "$TMP/bin/codex" <<'CODEX'
#!/usr/bin/env node
const fs=require('fs'),path=require('path'); const home=process.env.CODEX_HOME||process.env.HOME; fs.mkdirSync(home,{recursive:true}); fs.writeFileSync(path.join(home,'env.json'),JSON.stringify({OPENAI_API_KEY:process.env.OPENAI_API_KEY||null,ANTHROPIC_API_KEY:process.env.ANTHROPIC_API_KEY||null,ANTHROPIC_AUTH_TOKEN:process.env.ANTHROPIC_AUTH_TOKEN||null})); let buf='',thread='thread-fixture',threadPath=path.join(home,'sessions','odd','rollout--thread-fixture.jsonl'); function send(o){console.log(JSON.stringify(o));} function ensure(){fs.mkdirSync(path.dirname(threadPath),{recursive:true});fs.appendFileSync(threadPath,'{}\n');}
process.stdin.on('data',d=>{buf+=d;let i;while((i=buf.indexOf('\n'))>=0){const l=buf.slice(0,i);buf=buf.slice(i+1);if(!l.trim())continue;const r=JSON.parse(l);if(r.method==='initialize')send({jsonrpc:'2.0',id:r.id,result:{codexHome:home,userAgent:'stub'}});else if(r.method==='thread/start'){ensure();send({jsonrpc:'2.0',id:r.id,result:{thread:{id:thread,path:threadPath,status:{type:'idle'}},model:r.params.model,sandbox:r.params.sandbox,approvalPolicy:r.params.approvalPolicy}})}else if(r.method==='thread/resume'){thread=r.params.threadId;ensure();send({jsonrpc:'2.0',id:r.id,result:{thread:{id:thread,path:threadPath,status:{type:'idle'}},model:r.params.model}})}else if(r.method==='turn/start'||r.method==='turn/steer'){const turn='turn-1';send({jsonrpc:'2.0',id:r.id,result:{turn:{id:turn,status:'inProgress'}}});send({jsonrpc:'2.0',method:'thread/status/changed',params:{threadId:thread,status:{type:'active'}}});send({jsonrpc:'2.0',method:'turn/started',params:{threadId:thread,turn:{id:turn,status:'inProgress'}}});send({jsonrpc:'2.0',method:'item/started',params:{threadId:thread,item:{id:'tool-1',type:'commandExecution',command:'printf OK'}}});send({jsonrpc:'2.0',method:'item/completed',params:{threadId:thread,item:{id:'tool-1',type:'commandExecution',command:'printf OK',status:'completed',exitCode:0,output:'OK'}}});send({jsonrpc:'2.0',method:'item/completed',params:{threadId:thread,item:{id:'msg-1',type:'agentMessage',text:/RESUME/.test(JSON.stringify(r.params.input))?'RESUME_OK':'OK'}}});send({jsonrpc:'2.0',method:'thread/status/changed',params:{threadId:thread,status:{type:'idle'}}});send({jsonrpc:'2.0',method:'turn/completed',params:{threadId:thread,turn:{id:turn,status:'completed'}}});}}});
CODEX
chmod +x "$TMP/bin/codex"
printf 'brief\n' > "$TMP/proj/contracts/WORKER.md"; printf 'x\n' > "$TMP/proj/contracts/COMMANDER.md"; printf 'x\n' > "$TMP/proj/contracts/REVIEWER.md"
PATH="$TMP/bin:$PATH" HOME="$TMP/home" OPENAI_API_KEY=leak ANTHROPIC_API_KEY=leak ANTHROPIC_AUTH_TOKEN=leak bun "$ROOT/seats/drivers/codex/shim.ts" --log "$TMP/log.jsonl" --raw-log "$TMP/raw.jsonl" --err-log "$TMP/err.log" --account-dir "$TMP/home/codex" --brief "$TMP/proj/contracts/WORKER.md" --model gpt-5.5 --cwd "$TMP/proj" --actor worker-1 < <(printf '{"id":"s","type":"get_state"}\n{"id":"p","type":"prompt","message":"tools"}\n') & pid=$!
for i in {1..100}; do grep -q '"type":"agent_end"' "$TMP/log.jsonl" 2>/dev/null && break; sleep .1; done
kill "$pid" 2>/dev/null || true; wait "$pid" 2>/dev/null || true
grep -q '"sessionFile"' "$TMP/log.jsonl"; grep -q '"toolName":"shell"' "$TMP/log.jsonl"; grep -q '"type":"turn_end"' "$TMP/log.jsonl"; grep -q '"type":"agent_end"' "$TMP/log.jsonl"
! grep -q leak "$TMP/home/codex/env.json"
echo "codex.selftest: PASS (shim normalized events, thread.path, and stripped credential env vars)"
